version: '3'

services:
  mongo:
    image: mongo
    build: .
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Root828689
    ports:
      - 27017:27017
#  mongo:
#    build:
#      context: ./
#    ports:
#      - 27017:27017
#  mongo-backup:
#    image: tarator/mongodump:latest
#    restart: always
#    links:
#      - mongo
#    depends_on:
#      - mongo
#    volumes:
#     - ./mongo_backup:/backup:rw
#    environment:
#      - MONGO_HOST=mongo
#      - MONGO_PORT=27017
#      - BACKUP_CRON_TIME=*/2 * * * *
#      - KEEP_DAYS=14
# volumes:
#   mongo-backup:
