# docker-compose.yml file
version: '3.7'

services:
  # The load balancer
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "80:80"
  # The web server1
  server1:
    image: nginx:1.16.0-alpine
    volumes:
      - ./server1.html:/usr/share/nginx/html/index.html
  # The web server2
  server2:
    image: nginx:1.16.0-alpine
    volumes:
      - ./server2.html:/usr/share/nginx/html/index.html
  # The web server3
  server3:
    image: nginx:1.16.0-alpine
    volumes:
      - ./server3.html:/usr/share/nginx/html/index.html
  # The web server4
  server4:
    image: nginx:1.16.0-alpine
    volumes:
      - ./server4.html:/usr/share/nginx/html/index.html
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    restart: always
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    # - /usr/bin/docker:/usr/bin/docker
    # - /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6
    # - $(pwd)/docker-compose.yml:/app/docker-compose.yml
